server:
  port: 8080
  servlet:
    context-path: /spring-demo
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
#      username:
#      password:
      database: springdemo
      reactive-repositories:
        enabled: true
  profiles:
    active: dev,local
logging:
  level: debug